language: isabelle

before_install:
  - "wget http://isabelle.in.tum.de/dist/Isabelle2021_app.tar.gz"
  - "tar -xzf Isabelle2021_app.tar.gz"
  - "mkdir -p ~/.isabelle/Isabelle2021/heaps/polyml-5.8.2_x86_64_32-linux/"
  - "pushd ~/.isabelle/Isabelle2021/heaps/polyml-5.8.2_x86_64_32-linux/"
  - "wget http://yozora.eu/Isabelle2021_heap_prebuilt.tar.gz"
  - "tar -xzf Isabelle2021_heap_prebuilt.tar.gz"
  - "popd"

addons:
  apt:
    packages:
      - lib32stdc++6
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-fonts-recommended
      - texlive-generic-recommended
      - texlive-math-extra

script:
  - "cd ParityGame"
  - "../Isabelle2021/bin/isabelle build -o document=pdf -j 2 -v -d ../Coinductive/ -d ../Graph_Theory -D ."
